		<?php

		$class[11] = array(
			0 => array('range' => '', 'name' => 'Level 98','id'=> '', 'next' => array(
					0 => array( 'range' => '98 - 110', 'name' => 'A Summons From Moonglade','id'=> ''),
					1 => array( 'range' => '98 - 110', 'name' => 'Call of the Wilds','id'=> ''),
					2 => array( 'range' => '98 - 110', 'name' => 'The Dreamway','id'=> ''),
					3 => array( 'range' => '98 - 110', 'name' => 'To The Dreamgrove','id'=> ''),
					4 => array( 'range' => '98 - 110', 'name' => 'Weapons of Legend','id'=> ''),
					5 => array('range' => '', 'name' => 'Acquire the chosen artifact:','id'=> '', 'next' => array(			
							0 => array('range' => '', 'name' => 'Balance ( Scythe of Elune)','id'=> '', 'next' => array(					
									0 => array( 'range' => '98 - 110', 'name' => 'The Scythe of Elune','id'=> ''),
									1 => array( 'range' => '98 - 110', 'name' => 'Its Rightful Place','id'=> ''),
									2 => array( 'range' => '98 - 110', 'name' => 'A Foe of the Dark','id'=> ''),
									3 => array( 'range' => '98 - 110', 'name' => 'Following the Curse','id'=> ''),
									4 => array( 'range' => '98 - 110', 'name' => 'Disturbing the Past','id'=> ''),
									5 => array( 'range' => '98 - 110', 'name' => 'The Deadwind Hunt','id'=> ''),
									6 => array( 'range' => '98 - 110', 'name' => 'The Dark Riders','id'=> ''),
									7 => array( 'range' => '98 - 110', 'name' => 'The Burden Borne','id'=> ''),
								),
							),
							1 => array('range' => '', 'name' => 'Feral (Fangs of Ashamane: Fangs of Ashamane and Fangs of Ashamane)','id'=> '', 'next' => array(					
									0 => array( 'range' => '98 - 110', 'name' => 'The Shrine of Ashamane','id'=> ''),
									1 => array( 'range' => '98 - 110', 'name' => 'Aid for the Ashen', 'name1' => 'Seeds of Renewal','id'=> '','id1'=> ''),
									2 => array( 'range' => '98 - 110', 'name' => 'The Shrine in Peril','id'=> ''),
									3 => array( 'range' => '98 - 110', 'name' => 'The Fangs of Ashamane','id'=> ''),
								),
							),
							2 => array('range' => '', 'name' => 'Guardian (Claws of Ursoc: Claws of Ursoc and Claws of Ursoc)','id'=> '', 'next' => array(					
									0 => array( 'range' => '98 - 110', 'name' => 'Mistress of the Claw','id'=> ''),
									1 => array( 'range' => '98 - 110', 'name' => 'To The Hills','id'=> ''),
									2 => array( 'range' => '98 - 110', 'name' => 'Fallen Offerings','id'=> ''),
									3 => array( 'range' => '98 - 110', 'name' => 'The First Trial of Ursol','id'=> ''),
									4 => array( 'range' => '98 - 110', 'name' => 'The Second Trial of Ursol','id'=> ''),
									5 => array( 'range' => '98 - 110', 'name' => 'The Third Trial of Ursol','id'=> ''),
									6 => array( 'range' => '98 - 110', 'name' => 'When Dreams Become Nightmares','id'=> ''),
									8 => array( 'range' => '98 - 110', 'name' => 'The Dreamer Returns','id'=> ''),
								),
							),
							3 => array('range' => '', 'name' => 'Restoration ( G\'Hanir, the Mother Tree)','id'=> '', 'next' => array(					
									0 => array( 'range' => '98 - 110', 'name' => 'Meet with Mylune','id'=> ''),
									1 => array( 'range' => '98 - 110', 'name' => 'Necessary Preparations','id'=> ''),
									2 => array( 'range' => '98 - 110', 'name' => 'Join the Dreamer','id'=> ''),
									3 => array( 'range' => '98 - 110', 'name' => 'In Deep Slumber','id'=> ''),
									4 => array( 'range' => '98 - 110', 'name' => 'Reconvene','id'=> ''),
									5 => array( 'range' => '98 - 110', 'name' => 'Cleansing the Mother Tree','id'=> ''),
								),
							),
						),
					),
					6 => array( 'range' => '98 - 110', 'name' => 'Sowing The Seed','id'=> ''),
					7 => array( 'range' => '98 - 110', 'name' => 'The Seed of Ages','id'=> ''),
					8 => array( 'range' => '98 - 110', 'name' => 'Ascending The Circle','id'=> ''),
					9 => array( 'range' => '98 - 110', 'name' => 'Word on the Winds','id'=> ''),
					10 => array( 'range' => '98 - 110', 'name' => 'Making Trails','id'=> ''),
				),
			),
			1 => array('range' => '', 'name' => 'Level 101','id'=> '', 'next' => array(
					0 => array( 'range' => '101 - 110', 'name' => 'Growing Power','id'=> ''),
					1 => array('range' => '', 'name' => 'Complete all of:','id'=> '', 'next' => array(
							0 => array('range' => '101 - 110', 'name' => 'Rise, Champions','id'=> '', 'next' => array(
									0 => array( 'range' => '101 - 110', 'name' => 'Champion: Naralex','id'=> ''),
									1 => array( 'range' => '101 - 110', 'name' => 'Champion: Zen\'tabra','id'=> ''),
								),
							),
						),
					),
					2 => array( 'range' => '101 - 110', 'name' => 'Sister Lilith','id'=> ''),
					3 => array( 'range' => '101 - 110', 'name' => 'Recruiting the Troops','id'=> ''),
					4 => array( 'range' => '101 - 110', 'name' => 'A Glade Defense','id'=> ''),
					5 => array( 'range' => '101 - 110', 'name' => 'Branching Out','id'=> ''),
					6 => array( 'range' => '101 - 110', 'name' => 'Sampling the Nightmare','id'=> ''),
					7 => array( 'range' => '101 - 110', 'name' => 'Dire Growth','id'=> ''),
				),
			),
			2 => array('range' => '', 'name' => 'Level 103','id'=> '', 'next' => array(
					0 => array( 'range' => '103 - 110', 'name' => 'Malorne\'s Refuge','id'=> ''),
					1 => array( 'range' => '103 - 110', 'name' => 'Grip of Nightmare','id'=> ''),
					2 => array( 'range' => '103 - 110', 'name' => 'Tracking the Enemy','id'=> ''),
					3 => array( 'range' => '103 - 110', 'name' => 'Idol of the Wilds','id'=> ''),
					4 => array( 'range' => '103 - 110', 'name' => 'Gathering the Dreamweavers','id'=> ''),
					5 => array('range' => '103 - 110', 'name' => 'The Protectors','id'=> '', 'next' => array(
							0 => array('range' => '', 'name' => 'Optional','id'=> '', 'next' => array(
									0 => array( 'range' => '103 - 110D', 'name' => 'Halls of Valor: Essence of Ferocity','id'=> ''),
									1 => array( 'range' => '103 - 110D', 'name' => 'Eye of Azshara: Essence of Balance','id'=> ''),
									2 => array( 'range' => '103 - 110D', 'name' => 'Neltharion\'s Lair: Essence of Tenacity','id'=> ''),
									3 => array( 'range' => '103 - 110D', 'name' => 'Darkheart Thicket: Essence of Regrowth','id'=> ''),
								),
							),
						),
					),
					6 => array('range' => '', 'name' => 'Optional','id'=> '', 'next' => array(
							0 => array( 'range' => '103 - 110', 'name' => 'Druids of the Claw','id'=> ''),
							1 => array( 'range' => '103 - 110', 'name' => 'Champion: Broll Bearmantle','id'=> ''),
							2 => array( 'range' => '103 - 110', 'name' => 'Champion: Sylendra Gladesong','id'=> ''),
						),
					),
				),
			),
			3 => array('range' => '', 'name' => 'Level 110','id'=> '', 'next' => array(
					0 => array( 'range' => '110', 'name' => 'The Way to Nordrassil','id'=> ''),
					1 => array('range' => '', 'name' => 'Complete all of:','id'=> '', 'next' => array(
							0 => array( 'range' => '110', 'name' => 'Enduring the Nightmare','id'=> ''),
							1 => array( 'range' => '110', 'name' => 'Cleaning Up','id'=> ''),
							2 => array( 'range' => '110', 'name' => 'Teensy Weensies!','id'=> ''),
						),
					),
					2 => array( 'range' => '110', 'name' => 'A Dying Dream','id'=> ''),
					3 => array( 'range' => '110', 'name' => 'Communing With Malorne','id'=> ''),
					4 => array('range' => '110', 'name' => 'A New Beginning','id'=> '', 'next' => array(
							0 => array('range' => '', 'name' => 'Side quests:','id'=> '', 'next' => array(
									0 => array( 'range' => '110', 'name' => 'The Cycle Continues','id'=> ''),
									1 => array( 'range' => '110D', 'name' => 'Eye of Azshara: Cleansing the Dreamway','id'=> ''),
									2 => array('range' => '110', 'name' => 'The Pendant of Starlight','id'=> '', 'next' => array(
											0 => array( 'range' => '110', 'name' => 'Champion: Brightwing','id'=> ''),
										),
									),
								),
							),
						),
					),
					5 => array('range' => '', 'name' => 'Complete both:','id'=> '', 'next' => array(
							0 => array( 'range' => '110', 'name' => 'Champion: Mylune','id'=> ''),
							1 => array( 'range' => '110', 'name' => 'Champion: Hamuul Runetotem','id'=> ''),
						),
					),
					6 => array('range' => '', 'name' => 'Complete all of:','id'=> '', 'next' => array(
							0 => array( 'range' => '110', 'name' => 'Powering the Portal','id'=> ''),
							1 => array( 'range' => '110', 'name' => 'Defending the Isles','id'=> ''),
							2 => array( 'range' => '110', 'name' => 'Focusing the Energies','id'=> ''),
						),
					),
					7 => array( 'range' => '110', 'name' => 'Enter Nightmare','id'=> ''),
					8 => array( 'range' => '110', 'name' => 'Defenders of the Dream','id'=> ''),
					9 => array( 'range' => '110', 'name' => 'The War of the Ancients','id'=> ''),
					10 => array( 'range' => '110', 'name' => 'Archimonde, The Defiler','id'=> ''),
					11 => array( 'range' => '110', 'name' => 'The Demi-God\'s Return','id'=> ''),
					12 => array('range' => '110', 'name' => 'A Hero\'s Weapon','id'=> '', 'next' => array(
							0 => array('range' => '', 'name' => 'Side quests:','id'=> '', 'next' => array(
									0 => array( 'range' => '110', 'name' => 'Champion: Remulos','id'=> ''),
									1 => array( 'range' => '110R', 'name' => 'The Emerald Nightmare: The Emerald Nightmare','id'=> ''),
								),
							),
						),
					),
				),
			),
		);