<?php

$class[5] = array(
	0 => array('range' => '', 'name' => 'Level 98','id'=> '', 'next' => array(
			0 => array( 'range' => '98 - 110', 'name' => 'Priestly Matters','id'=> ''),
			1 => array( 'range' => '98 - 110', 'name' => 'A Legend You Can Hold','id'=> ''),
			2 => array('range' => '', 'name' => 'Acquire the chosen artifact:','id'=> '', 'next' => array(
					0 => array('range' => '', 'name' => 'Discipline ( Light\'s Wrath)','id'=> '', 'next' => array(
							0 => array( 'range' => '98 - 110', 'name' => 'The Light\'s Wrath','id'=> ''),
							1 => array( 'range' => '98 - 110', 'name' => 'A New Threat','id'=> ''),
							2 => array( 'range' => '98 - 110', 'name' => 'A Forgotten Enemy','id'=> ''),
							3 => array( 'range' => '98 - 110', 'name' => 'Eyes of the Dragon','id'=> ''),
							4 => array( 'range' => '98 - 110', 'name' => 'Harnessing the Holy Fire','id'=> ''),
							5 => array( 'range' => '98 - 110', 'name' => 'Unleashing Judgment','id'=> ''),
							6 => array( 'range' => '98 - 110', 'name' => 'The Nexus Vault','id'=> ''),
							7 => array( 'range' => '98 - 110', 'name' => 'A Gift of Time','id'=> ''),
						),
					),
					1 => array('range' => '', 'name' => 'Holy ( T\'uure, Beacon of the Naaru)','id'=> '', 'next' => array(
							0 => array( 'range' => '98 - 110', 'name' => 'The Vindicator\'s Plea','id'=> ''),
							1 => array( 'range' => '98 - 110', 'name' => 'House Call','id'=> ''),
							2 => array( 'range' => '98 - 110', 'name' => 'Out of the Darkness','id'=> ''),
							3 => array( 'range' => '98 - 110', 'name' => 'Salvation From On High','id'=> ''),
							4 => array( 'range' => '98 - 110', 'name' => 'Return of the Light','id'=> ''),
						),
					),
					2 => array('range' => '', 'name' => 'Shadow ( Xal\'atath, Blade of the Black Empire)','id'=> '', 'next' => array(
							0 => array( 'range' => '98 - 110', 'name' => 'Blade in Twilight','id'=> ''),
						),
					),
				),
			),
			3 => array( 'range' => '98 - 110', 'name' => 'The Light and the Void','id'=> ''),
			4 => array( 'range' => '98 - 110', 'name' => 'Artifacts Need Artificers','id'=> ''),
			5 => array( 'range' => '98 - 110', 'name' => 'Empowering Your Artifact','id'=> ''),
			6 => array( 'range' => '98 - 110', 'name' => 'Actions on Azeroth','id'=> ''),
		),
	),
	1 => array('range' => '', 'name' => 'Level 101', 'id'=> '', 'next' => array(
			0 => array('range' => '', 'name' => 'Complete all of:','id'=> '', 'next' => array(
					0 => array('range' => '101 - 110', 'name' => 'Rise, Champions','id'=> '', 'next' => array(
							0 => array( 'range' => '101 - 110', 'name' => 'Champion: Calia Menethil','id'=> ''),
							1 => array( 'range' => '101 - 110', 'name' => 'Champion: High Priestess Ishanah','id'=> ''),
						),
					),
				),
			),
			1 => array( 'range' => '101 - 110', 'name' => 'Spread the Word','id'=> ''),
			2 => array( 'range' => '101 - 110', 'name' => 'Recruiting the Troops','id'=> ''),
			3 => array( 'range' => '101 - 110', 'name' => 'Troops in the Field','id'=> ''),
			4 => array( 'range' => '101 - 110', 'name' => 'Tech It Up A Notch','id'=> ''),
			5 => array( 'range' => '101 - 110', 'name' => 'Relieving the Front Lines','id'=> ''),
		),
	),
	2 => array('range' => '', 'name' => 'Level 103', 'id'=> '', 'next' => array(
			0 => array( 'range' => '103 - 110', 'name' => 'Whispers in the Void','id'=> ''),
			1 => array( 'range' => '103 - 110', 'name' => 'The Best and Brightest','id'=> ''),
			2 => array('range' => '', 'name' => 'Complete both:','id'=> '', 'next' => array(
					0 => array( 'range' => '103 - 110', 'name' => 'Murloc Mind Control','id'=> ''),
					1 => array( 'range' => '103 - 110', 'name' => 'An Ample Supply','id'=> ''),
				),
			),
			3 => array( 'range' => '103 - 110', 'name' => 'Problem Salver','id'=> ''),
			4 => array('range' => '', 'name' => 'Complete both:','id'=> '', 'next' => array(
					0 => array( 'range' => '103 - 110', 'name' => 'Champion: Yalia Sagewhisper','id'=> ''),
					1 => array( 'range' => '103 - 110', 'name' => 'Champion: Zabra Hexx','id'=> ''),
				),
			),
			5 => array( 'range' => '103 - 110D', 'name' => 'Eye of Azshara: Looking Through the Lens','id'=> ''),
			6 => array( 'range' => '103 - 110', 'name' => 'Velen\'s Vision','id'=> ''),
			7 => array('range' => '', 'name' => 'Complete all of:','id'=> '', 'next' => array(
					0 => array( 'range' => '103 - 110D', 'name' => 'Halls of Valor: The Light Within','id'=> ''),
					1 => array( 'range' => '103 - 110', 'name' => 'Demonic Runes','id'=> ''),
					2 => array( 'range' => '103 - 110', 'name' => 'Recruiting More Troops','id'=> ''),
				),
			),
			8 => array( 'range' => '103 - 110', 'name' => 'Awakening the Light','id'=> ''),
			9 => array( 'range' => '103 - 110', 'name' => 'Champion: Sol','id'=> ''),
		),
	),
	3 => array('range' => '', 'name' => 'Level 110','id'=> '', 'next' => array(
			0 => array( 'range' => '110', 'name' => 'Infiltrating Our Enemies','id'=> ''),
			1 => array( 'range' => '110', 'name' => 'Onslaught Envoy','id'=> ''),
			2 => array('range' => '', 'name' => 'Complete both:','id'=> '', 'next' => array(
					0 => array( 'range' => '110', 'name' => 'Scarlet Redemption','id'=> ''),
					1 => array( 'range' => '110', 'name' => 'Apostate Liberation','id'=> ''),
				),
			),
			3 => array( 'range' => '110', 'name' => 'Unexpected Guests','id'=> ''),
			4 => array( 'range' => '110', 'name' => 'Champion: Mariella Ward','id'=> ''),
			5 => array( 'range' => '110', 'name' => 'Forgotten Shadows','id'=> ''),
			6 => array( 'range' => '110', 'name' => 'Secrets of the Void','id'=> ''),
			7 => array( 'range' => '110', 'name' => 'Into the Void','id'=> ''),
			8 => array( 'range' => '110', 'name' => 'Champion: Natalie Seline','id'=> ''),
			9 => array( 'range' => '110', 'name' => 'Rising Shadows','id'=> ''),
			10 => array( 'range' => '110', 'name' => 'Crossing Legion Lines','id'=> ''),
			11 => array('range' => '', 'name' => 'Complete both:','id'=> '', 'next' => array(
					0 => array( 'range' => '110', 'name' => 'The Mind of the Enemy','id'=> ''),
					1 => array( 'range' => '110', 'name' => 'Allies of the Light','id'=> ''),
				),
			),
			12 => array( 'range' => '110', 'name' => 'United As One','id'=> ''),
			13 => array( 'range' => '110', 'name' => 'Aiding the Conclave','id'=> ''),
			14 => array('range' => '', 'name' => 'Complete all of:','id'=> '', 'next' => array(
					0 => array('range' => '110', 'name' => 'Elixirs of Aid','id'=> '', 'next' => array(
							0 => array('range' => '', 'name' => '<i>Repeatable quests:</i>','id'=> '', 'next' => array(
									0 => array( 'range' => '110', 'name' => 'Starlight Rose','id'=> ''),
									1 => array( 'range' => '110', 'name' => 'Runescale Koi','id'=> ''),
									2 => array( 'range' => '110', 'name' => 'Leyblood','id'=> ''),
								),
							),
						),
					),
					1 => array( 'range' => '110', 'name' => 'Fortifying the Temple','id'=> ''),
					2 => array( 'range' => '110', 'name' => 'Lumenstone','id'=> ''),
				),
			),
			15 => array( 'range' => '110', 'name' => 'A Light in the Darkness','id'=> ''),
			16 => array( 'range' => '110', 'name' => 'High Priest of Netherlight','id'=> ''),
			17 => array( 'range' => '110', 'name' => 'Champion: Alonsus Faol','id'=> ''),
		),
	),
);