		<?php

		$class[9] = array(
			0 => array('range' => '', 'name' => 'Level 98','id'=> '', 'next' => array(
					0 => array( 'range' => '98 - 110', 'name' => 'The Sixth','id'=> ''),
					1 => array( 'range' => '98 - 110', 'name' => 'The New Blood','id'=> ''),
					2 => array( 'range' => '98 - 110', 'name' => 'The Tome of Blighted Implements','id'=> ''),
					3 => array('range' => '', 'name' => 'Acquire the chosen artifact:','id'=> '', 'next' => array(
							0 => array('range' => '', 'name' => 'Affliction ( Ulthalesh, the Deadwind Harvester)','id'=> '', 'next' => array(
									0 => array( 'range' => '98 - 110', 'name' => 'Ulthalesh, the Deadwind Harvester','id'=> ''),
									1 => array( 'range' => '98 - 110', 'name' => 'Following the Curse','id'=> ''),
									2 => array( 'range' => '98 - 110', 'name' => 'Disturbing the Past','id'=> ''),
									3 => array( 'range' => '98 - 110', 'name' => 'To Point the Way','id'=> ''),
									4 => array( 'range' => '98 - 110', 'name' => 'The Fate of Deadwind','id'=> ''),
									5 => array( 'range' => '98 - 110', 'name' => 'The Dark Riders','id'=> ''),
									6 => array( 'range' => '98 - 110', 'name' => 'The Power Possessed','id'=> ''),
								),
							),
							1 => array('range' => '', 'name' => 'Demonology ( Skull of the Man\'ari)','id'=> '', 'next' => array(
									0 => array( 'range' => '98 - 110', 'name' => 'Ritual Reagents','id'=> ''),
									1 => array( 'range' => '98 - 110', 'name' => 'Looking into the Darkness','id'=> ''),
									2 => array( 'range' => '98 - 110', 'name' => 'Dark Whispers','id'=> ''),
								),
							),
							2 => array('range' => '', 'name' => 'Destruction ( Scepter of Sargeras)','id'=> '', 'next' => array(
									0 => array( 'range' => '98 - 110', 'name' => 'Finding the Scepter','id'=> ''),
									1 => array( 'range' => '98 - 110', 'name' => 'An Eye for a Scepter','id'=> ''),
									2 => array( 'range' => '98 - 110', 'name' => 'Ritual Ruination','id'=> ''),
								),
							),
						),
					),
					3 => array( 'range' => '98 - 110', 'name' => 'The Heart of the Dreadscar','id'=> ''),
					4 => array( 'range' => '98 - 110', 'name' => 'Power Overwhelming','id'=> ''),
					5 => array( 'range' => '98 - 110', 'name' => 'Rebuilding the Council','id'=> ''),
					6 => array( 'range' => '98 - 110', 'name' => 'The Path of the Dreadscar','id'=> ''),
				),
			),
			1 => array('range' => '', 'name' => 'Level 101','id'=> '', 'next' => array(
					0 => array( 'range' => '101 - 110', 'name' => 'A Mutual Friend','id'=> ''),
					1 => array('range' => '101 - 110', 'name' => 'Rise, Champions','id'=> '', 'next' => array(
							0 => array( 'range' => '101 - 110', 'name' => 'Champion: Calydus','id'=> ''),
							1 => array( 'range' => '101 - 110', 'name' => 'Champion: Ritssyn Flamescowl','id'=> ''),
						),
					),
					2 => array( 'range' => '101 - 110', 'name' => 'Information at Any Cost','id'=> ''),
					3 => array( 'range' => '101 - 110', 'name' => 'Recruiting The Troops','id'=> ''),
					4 => array( 'range' => '101 - 110', 'name' => 'Troops in the Field','id'=> ''),
					5 => array( 'range' => '101 - 110', 'name' => 'Tech It Up A Notch','id'=> ''),
					6 => array( 'range' => '101 - 110', 'name' => 'Searching the Archives','id'=> ''),
				),
			),
			2 => array('range' => '', 'name' => 'Level 103','id'=> '', 'next' => array(
					0 => array( 'range' => '103 - 110', 'name' => 'An Unlikely Ally','id'=> ''),
					1 => array( 'range' => '103 - 110', 'name' => 'Bloodstone Bandit','id'=> ''),
					2 => array( 'range' => '103 - 110', 'name' => 'It Hungers for Blood','id'=> ''),
					3 => array( 'range' => '103 - 110', 'name' => 'Testing a Theory','id'=> ''),
					4 => array( 'range' => '103 - 110', 'name' => 'Debt Repaid','id'=> ''),
					5 => array( 'range' => '103 - 110', 'name' => 'A Daring Rescue','id'=> ''),
					6 => array('range' => '', 'name' => 'Complete both:','id'=> '', 'next' => array(
							0 => array( 'range' => '103 - 110', 'name' => 'Champion: Jubeka Shadowbreaker','id'=> ''),
							1 => array( 'range' => '103 - 110', 'name' => 'Champion: Zinnin Smythe','id'=> ''),
						),
					),
					7 => array('range' => '103 - 110', 'name' => 'Empowering the Soul','id'=> '', 'next' => array(
							0 => array( 'range' => '', 'name' => 'Recruiting More Troops','id'=> ''),
						),
					),
				),
			),
			3 => array('range' => '', 'name' => 'Level 110','id'=> '', 'next' => array(
					0 => array( 'range' => '110D', 'name' => 'Black Rook Hold: An Unclaimed Soul','id'=> ''),
					1 => array( 'range' => '110', 'name' => 'Soul Beacon','id'=> ''),
					2 => array( 'range' => '110', 'name' => 'Mad Ernie the Alchemist','id'=> ''),
					3 => array( 'range' => '110', 'name' => 'Herding Goats','id'=> ''),
					4 => array( 'range' => '110', 'name' => 'Doom and Gloom','id'=> ''),
					5 => array( 'range' => '110', 'name' => 'Borrowed Time','id'=> ''),
					6 => array('range' => '', 'name' => 'Complete both:','id'=> '', 'next' => array(
							0 => array( 'range' => '110', 'name' => 'Champion: Shinfel Blightsworn','id'=> ''),
							1 => array( 'range' => '110', 'name' => 'Champion: Kira Iresoul','id'=> ''),
						),
					),
					7 => array('range' => '', 'name' => 'Complete all of:','id'=> '', 'next' => array(
							0 => array( 'range' => '110', 'name' => 'One Who\'s Worthy','id'=> ''),
							1 => array( 'range' => '110D', 'name' => 'Vault of the Wardens: Matters of the Heart','id'=> ''),
							2 => array( 'range' => '110', 'name' => 'Let it Feed','id'=> ''),
							3 => array( 'range' => '110', 'name' => 'Unparalleled Power','id'=> ''),
						),
					),
					8 => array( 'range' => '110', 'name' => 'Finding Fizzlebang','id'=> ''),
					9 => array('range' => '', 'name' => 'Complete both:','id'=> '', 'next' => array(
							0 => array( 'range' => '110', 'name' => 'Coercing a Confession','id'=> ''),
							1 => array( 'range' => '110', 'name' => 'Someone Else\'s Mess','id'=> ''),
						),
					),
					10 => array( 'range' => '110', 'name' => 'Lulubelle on Loan','id'=> ''),
					11 => array( 'range' => '110', 'name' => 'Champion: Lulubelle Fizzlebang','id'=> ''),
					12 => array( 'range' => '110', 'name' => 'Summoning the Sisters','id'=> ''),
					13 => array( 'range' => '110', 'name' => 'Selecting a Sixth','id'=> ''),
					14 => array( 'range' => '110', 'name' => 'Champion: Eredar Twins','id'=> ''),
					15 => array( 'range' => '110', 'name' => 'A Hero\'s Weapon','id'=> ''),
				),
			),
		);